@extends('frontend.layouts.app-page')

@section('title',  'Cookies Policy')

@section('content')
        <main class="main">
            <div class="page-header" style="background-color:white;height:35px; padding-top:30px;">
                <h1 class="page-title"> Cookies Policy</h1>
            </div>
            <div class="page-content mt-10 pt-7">
                <section class="about-section">
                    <div class="container">
                        <div class="row mb-10">
                           
                           
  

                            <div>
<h5>What are Cookies?</h5>
<p>Cookies are small text files that are stored by the browser (for example, Internet Explorer) on your computer or device. You can think of cookies as providing a memory for the website, so that it can recognise you when you come back and respond appropriately. 
</p>
<h5>How we use Cookies?</h5>
<p>We use cookies to understand your use of our Services; improve client experience and enable personalised features and content; optimise our advertisements and marketing; and to enable third-party advertising firms to assist us in serving ads specific to your interests. 
</p><h5>Are cookies harmful to my computer?</h5>
<p>No they’re not dangerous for your computer and they do not in any means infringe your privacy rights. Cookies are, in fact, nothing more than very small text files that are placed on your computer/browser when you visit our website.
</p><h5>Third-party Cookies</h5>
<p>
When visiting our website, you may receive cookies both from the site being visited and from websites managed by alternative organizations ("third parties"). A notable example is that the presence of "social plugins" for Facebook, Twitter, Google+, LinkedIn, etc. Such sections of the page visited are directly generated by these websites and integrated into the page of the host website. The management of the information collected by "third parties" is governed by their relevant policies The privacy policies ruled by "third parties" may be completely different from the one adopted by us, therefore we do not respond to third-party sites. 
</br><span style="color:#05B895;"><a href="https://www.adroll.com">www.adroll.com</a></span> - Digital Marketing, Targeted Advertising
</br><span style="color:#05B895;"><a href="https://www.bazaarvoice.com">www.bazaarvoice.com</a></span> - Digital Marketing and review service, collects data for use in interest based advertising
</br><span style="color:#05B895;"><a href="https:/www.google.com/analytics">www.google.com/analytics</a></span> - Web Analytics, Measures user interaction on our websites
</br><span style="color:#05B895;"><a href="https://www.qubit.com">www.qubit.com</a></span> - Measures how customers use our website, and how the website behaves when used by visitors.
</br><span style="color:#05B895;"><a href="https://www.cloudflare.com">www.cloudflare.com</a></span>- Used for web performance and security
</br><span style="color:#05B895;"><a href="https://www.iban.com">www.iban.com</a></span> - Used for bank account validation
</br><span style="color:#05B895;"><a href="https://www.loqate.com ">www.loqate.com </a></span>- Used for location intelligence
</br><span style="color:#05B895;"><a href="https://pricespy.co.uk">pricespy.co.uk</a></span> - Used for Price Comparison - Authentication, tracking of search history, last visited products, and many generic settings
</br><span style="color:#05B895;"><a href="https://www.kelkoo.com ">www.kelkoo.com </a></span>- Used for Price Comparison - estimate audience size and usage pattern, store your preferences, speed up your searches, statistics 
</p><p><h5>What are your choices regarding Cookies?</h5>
When you first log in we provide you the option to personalise your cookie set up so you can decide which types of cookies you want us to use. It is worth noting that our website along with most others wouldn’t work very well without certain cookies. They allow us to prevent crashes, display information, fix bugs and ensure the security of our site (and your account). These types of cookies are often called “Required” cookies. Because they are needed for our site to work, we don’t provide you with an ability to opt-out of these cookies. But you can remove them by using your browser settings. Keep in mind that certain features of our site may not be available to you. 
</p><p>For more information on how to manage cookies in your browser, please visit <span style="color:#05B895;"><a href="www.allaboutcookies.org/manage-cookies">www.allaboutcookies.org/manage-cookies</a></span> . 
</p><p>You can also learn more about interest based advertising and your rights here <span style="color:#05B895;"><a href="youradchoices.com">youradchoices.com</a></span> </p>



                            
                            </div>
                        </div>
                    </div>

                    
                </section>
                <!-- End About Section-->

                <!-- End Clients Section -->
            </div>
        </main>
        <style>
            .list-circle i {
                background-color: aliceblue;
            }

            </style>
      @endsection